/*#pragma aux ClockCycles
#pragma aux __inline_InterruptEnable
#pragma aux __inline_InterruptDisable
extern unsigned __cpu_flags;
#pragma aux __inline_InterruptUnlock
#pragma aux __inline_InterruptLock
#pragma aux __inline_InterruptStatus
#pragma aux __inline_DebugBreak
#pragma aux __inline_DebugKDBreak
#pragma aux __inline_DebugKDOutput*/
